package com.mealotopia.client.model.data_class.meal

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class DetailMealResponse(
    var idMeal: String?= null,
    var strMeal: String?= null,
    var strDrinkAlternate: String?= null,
    var strCategory: String?= null,
    var strArea: String?= null,
    var strInstructions: String?= null,
    var strMealThumb: String?= null,
    var strTags: String?= null,
    var strYoutube: String?= null,
    var strIngridient1: String?= null,
    var strIngridient2: String?= null,
    var strIngridient3: String?= null,
    var strIngridient4: String?= null,
    var strIngridient5: String?= null,
    var strIngridient6: String?= null,
    var strIngridient7: String?= null,
    var strIngridient8: String?= null,
    var strIngridient9: String?= null,
    var strIngridient10: String?= null,
    var strIngridient11: String?= null,
    var strIngridient12: String?= null,
    var strIngridient13: String?= null,
    var strIngridient14: String?= null,
    var strIngridient15: String?= null,
    var strIngridient16: String?= null,
    var strIngridient17: String?= null,
    var strIngridient18: String?= null,
    var strIngridient19: String?= null,
    var strIngridient20: String?= null,
    var strMeasure1: String?= null,
    var strMeasure2: String?= null,
    var strMeasure3: String?= null,
    var strMeasure4: String?= null,
    var strMeasure5: String?= null,
    var strMeasure6: String?= null,
    var strMeasure7: String?= null,
    var strMeasure8: String?= null,
    var strMeasure9: String?= null,
    var strMeasure10: String?= null,
    var strMeasure11: String?= null,
    var strMeasure12: String?= null,
    var strMeasure13: String?= null,
    var strMeasure14: String?= null,
    var strMeasure15: String?= null,
    var strMeasure16: String?= null,
    var strMeasure17: String?= null,
    var strMeasure18: String?= null,
    var strMeasure19: String?= null,
    var strMeasure20: String?= null,
    var strSource: String?= null,
    var strImageSource: String?= null,
    var strCreativeCommonsConfirmed: String?= null,
    var dateModified: String?= null,
):Parcelable